;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        end-of-visual-line
        kill-region
        org-self-insert-command
        smart-hungry-delete-backward-char
        ))

(setq mc/cmds-to-run-once
      '(
        ))
