;; sets up all the settings for different modes

(add-hook 'prog-mode-hook (lambda ()
                            ;; (beacon-mode 1)
                            (dimmer-mode 1)
                            ;; (nyan-mode 1)
                            (global-company-mode 1)
                            ;; (global-aggressive-indent-mode 1)
                            (rainbow-delimiters-mode 1)
                            ;; (global-color-identifiers-mode 1)
                            ;; (indent-guide-global-mode 1)
                            (global-undo-tree-mode 1)
			    ;; (smooth-scrolling-mode 1)
                            ;; (lsp)
                            ;; (yas-global-mode 1)
                            (smartparens-global-mode 1)
                            (column-number-mode 1)
                            (outline-minor-mode)
                            ))

(add-hook 'dired-mode-hook (lambda ()
                             (put 'dired-find-alternate-file 'disabled nil) ;disables the warning
                             ;; (dired-hide-details-mode 1)
                             (setq dired-dwim-target t)
                             (all-the-icons-dired-mode)
                             (require 'dired-x)
                             ))

(add-hook 'web-mode-hook (lambda ()
                           (emmet-mode)
                           (web-mode-set-engine "django")
                           (electric-pair-mode -1)
                           (rainbow-mode 1)
                           (smartparens-mode -1)
                           ))

(add-hook 'magit-mode-hook (lambda ()
                             (global-git-gutter-mode)
                             ;; (add-hook 'magit-popup-hook ' (lambda () (modalka-mode -1)))
                             ))
(add-hook 'python-mode-hook (lambda ()
                              (elpy-enable)
                              (setq elpy-rpc-python-command "python3") ;only if you're using python3
                              ))
(add-hook 'org-mode-hook (lambda ()
                           (org-indent-mode)
                           ))
(add-hook 'tuareg-mode-hook (lambda ()
                              (merlin-mode 1)
                              (general-define-key
                               "C-c r" 'tuareg-eval-region
                               )
                              (company-mode -1)
                              (column-marker-1 79)
                              (column-marker-2 80)
                              ;; (whitespace-mode 1)
                              ))
(add-hook 'c-mode-hook (lambda ()
                         (column-marker-1 72)
                         (column-marker-2 73)
                         ;; (whitespace-mode 1)
                         ;; (semantic-mode 1)
                         ))

(provide 'my-modes)
